[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dtm"
version = "0.1.0"
description = "Debugging Time Machine"
requires-python = ">=3.11"
dependencies = [
    "click",
    "GitPython",
    "requests",
    "pytest",
    "ruff",
]

[project.scripts]
dtm = "dtm.cli:cli"

[project.optional-dependencies]
dev = [
    "pytest-cov",
]

[tool.ruff]
line-length = 100

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
